// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ReadingNotesServices.Models
{
    public partial class Config
    {
        private string _lastBookmarkDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string LastBookmarkDate
        {
            get { return this._lastBookmarkDate; }
            set { this._lastBookmarkDate = value; }
        }
        
        private int? _readingNotesCounter;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ReadingNotesCounter
        {
            get { return this._readingNotesCounter; }
            set { this._readingNotesCounter = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Config class.
        /// </summary>
        public Config()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken lastBookmarkDateValue = inputObject["last_bookmark_date"];
                if (lastBookmarkDateValue != null && lastBookmarkDateValue.Type != JTokenType.Null)
                {
                    this.LastBookmarkDate = ((string)lastBookmarkDateValue);
                }
                JToken readingNotesCounterValue = inputObject["reading_notes_counter"];
                if (readingNotesCounterValue != null && readingNotesCounterValue.Type != JTokenType.Null)
                {
                    this.ReadingNotesCounter = ((int)readingNotesCounterValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Config
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.LastBookmarkDate != null)
            {
                outputObject["last_bookmark_date"] = this.LastBookmarkDate;
            }
            if (this.ReadingNotesCounter != null)
            {
                outputObject["reading_notes_counter"] = this.ReadingNotesCounter.Value;
            }
            return outputObject;
        }
    }
}
